"""Private Live View snapshots and their authenticated Resource source."""
from __future__ import annotations

import json
from datetime import timedelta, timezone

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import JSONResponse, PlainTextResponse
from pydantic import BaseModel
from sqlalchemy import select

from agentplatform.api.live_views import (
    TypedDefinition,
    _accessible_app,
    _reader,
    read_live_view_data,
)
from agentplatform.db import LiveSnapshot, LiveView, LiveViewVersion, utcnow

router = APIRouter()
RETENTION = timedelta(days=30)
MAX_CONTENT_BYTES = 32 * 1024
PRIVATE = {"Cache-Control": "private, no-store"}


class CaptureIn(BaseModel):
    alias: str


def _active(row: LiveSnapshot, principal: str) -> None:
    expires = row.expires_at.replace(tzinfo=row.expires_at.tzinfo or timezone.utc)
    if row.owner_id != principal or row.deleted_at is not None or expires <= utcnow():
        raise HTTPException(404, "unknown snapshot")


def _metadata(row: LiveSnapshot) -> dict:
    return {"id": row.id, "view_id": row.view_id,
            "view_version": row.view_version, "title": row.title,
            "created_at": row.created_at.isoformat(),
            "expires_at": row.expires_at.isoformat(),
            "resource_uri": f"ap://snapshot/{row.id}"}


@router.post("/api/live-views/{view_id}/snapshots", status_code=201)
async def capture_live_snapshot(request: Request, view_id: str, body: CaptureIn,
                                ident: tuple[str, str] = Depends(_reader)):
    async with request.app.state.session_factory() as session:
        view = await session.get(LiveView, view_id)
        if view is None or view.published_version is None:
            raise HTTPException(404, "unknown view")
        await _accessible_app(session, view.app_name, ident)
        version = await session.get(LiveViewVersion, (view_id, view.published_version))
        if version is None:
            raise HTTPException(503, "published version unavailable")
        definition = TypedDefinition.model_validate(version.definition)
        if body.alias not in {read.alias for read in definition.reads}:
            raise HTTPException(404, "unknown read")
        captured_version = view.published_version
        title = definition.title

    # Reuse the exact ACL and bounded adapter serving the live page.
    response = await read_live_view_data(request, view_id, body.alias, ident)
    content = {body.alias: json.loads(response.body)}
    if len(json.dumps(content, ensure_ascii=False).encode()) > MAX_CONTENT_BYTES:
        raise HTTPException(413, "snapshot too large")
    async with request.app.state.session_factory() as session:
        view = await session.get(LiveView, view_id)
        if view is None or view.published_version != captured_version:
            raise HTTPException(409, "page changed during capture; retry")
        row = LiveSnapshot(view_id=view_id, view_version=captured_version,
                           owner_id=ident[0], title=title, content=content,
                           expires_at=utcnow() + RETENTION)
        session.add(row)
        await session.commit()
        return JSONResponse(_metadata(row), status_code=201, headers=PRIVATE)


@router.get("/api/live-snapshots")
async def list_live_snapshots(request: Request,
                              ident: tuple[str, str] = Depends(_reader)):
    async with request.app.state.session_factory() as session:
        rows = (await session.execute(select(LiveSnapshot).where(
            LiveSnapshot.owner_id == ident[0],
            LiveSnapshot.deleted_at.is_(None),
            LiveSnapshot.expires_at > utcnow()).order_by(
                LiveSnapshot.created_at.desc()).limit(50))).scalars().all()
        return JSONResponse([_metadata(row) for row in rows], headers=PRIVATE)


@router.get("/api/live-snapshots/{snapshot_id}")
async def get_live_snapshot(request: Request, snapshot_id: str,
                            ident: tuple[str, str] = Depends(_reader)):
    async with request.app.state.session_factory() as session:
        row = await session.get(LiveSnapshot, snapshot_id)
        if row is None:
            raise HTTPException(404, "unknown snapshot")
        _active(row, ident[0])
        return JSONResponse({**_metadata(row), "content": row.content}, headers=PRIVATE)


@router.get("/api/live-snapshots/{snapshot_id}/resource")
async def read_live_snapshot_resource(request: Request, snapshot_id: str,
                                      ident: tuple[str, str] = Depends(_reader)):
    async with request.app.state.session_factory() as session:
        row = await session.get(LiveSnapshot, snapshot_id)
        if row is None:
            raise HTTPException(404, "unknown snapshot")
        _active(row, ident[0])
        # Text is generated by the trusted server, never executable markup.
        text = f"# {row.title}\n\n" + json.dumps(row.content, ensure_ascii=False,
                                                   indent=2, sort_keys=True)
        return PlainTextResponse(text, media_type="text/markdown", headers=PRIVATE)


@router.delete("/api/live-snapshots/{snapshot_id}")
async def delete_live_snapshot(request: Request, snapshot_id: str,
                               ident: tuple[str, str] = Depends(_reader)):
    async with request.app.state.session_factory() as session:
        row = await session.get(LiveSnapshot, snapshot_id)
        if row is None:
            raise HTTPException(404, "unknown snapshot")
        _active(row, ident[0])
        row.deleted_at = utcnow()
        await session.commit()
        return JSONResponse({"deleted": True}, headers=PRIVATE)
