"""Reports: dated HTML artifacts of git-declared report types
(docs/design/11). Types are building blocks (reports/<name>/report.yaml,
reportregistry); instances are sanitized fragments in Postgres, identity
type/YYYY-MM-DD[/HH-MM], upserted idempotently so a re-run replaces its
report. The viewer wraps fragments in the report-kit shell client-side."""
import re

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, Field
from sqlalchemy import delete, func, select

from agentplatform.api import schemas as S
from agentplatform.api.auth import ANNOTATE_ROLES, READ_ROLES, require_admin, require_role
from agentplatform.db import Report
from agentplatform.reportcharts import ChartSpec, render_chart
from agentplatform.reportsanitize import sanitize_report_html

router = APIRouter()

_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_TIME = re.compile(r"^\d{2}-\d{2}$")
_MAX_HTML = 2_000_000  # 2 MB of fragment is a malfunctioning generator


def _registry(request: Request):
    reg = request.app.state.report_registry
    reg.reload()
    return reg


@router.get("/api/report-types", response_model=list[S.ReportTypeView],
            dependencies=[Depends(require_role(*READ_ROLES))])
async def list_report_types(request: Request):
    """Declared report types (the git blocks) with instance stats."""
    reg = _registry(request)
    async with request.app.state.session_factory() as s:
        rows = (await s.execute(
            select(Report.type, func.count(), func.max(Report.date))
            .group_by(Report.type))).all()
    stats = {t: (c, latest) for t, c, latest in rows}
    out = []
    for info in reg.list():
        count, latest = stats.get(info.name, (0, None))
        sp = info.spec
        out.append({"name": info.name,
                    "description": sp.description if sp else "",
                    "icon": sp.icon if sp else "",
                    "generator": sp.generator if sp else "",
                    "cadence": sp.cadence if sp else "",
                    "retention_days": sp.retention_days if sp else 0,
                    "error": info.error, "count": count, "latest_date": latest})
    return out


class ReportIn(BaseModel):
    type: str
    date: str                       # YYYY-MM-DD
    time: str = ""                  # HH-MM for intraday reports
    title: str = ""
    meta: dict = Field(default_factory=dict)
    html: str                       # body fragment; sanitized on ingest


@router.post("/api/reports", response_model=S.ReportSaved, status_code=201)
async def save_report(request: Request, body: ReportIn,
                      principal: str = Depends(require_role(*ANNOTATE_ROLES))):
    """Save (or idempotently replace) a report instance. The declared
    `generator` is the write ACL for machine keys: it may name an agent (the
    key's agent scope must match) or an app key by principal name (e.g.
    `app:news`). Admin sessions always may. HTML is sanitized through the
    report-kit allow-list; what you store is what the viewer shows."""
    reg = _registry(request)
    info = reg.get(body.type)
    if info is None:
        raise HTTPException(422, f"unknown report type `{body.type}` — declare "
                                 "reports/<name>/report.yaml first")
    if info.spec is None:
        raise HTTPException(422, f"report type `{body.type}` is broken: {info.error}")
    agent = getattr(request.state, "api_key_agent", None)
    is_api_key = hasattr(request.state, "api_key_run_id")
    gen = info.spec.generator
    if is_api_key and agent != gen and principal != gen:
        raise HTTPException(403, f"`{body.type}` is generated by "
                                 f"`{gen}`, not `{agent or principal}`")
    if not _DATE.match(body.date):
        raise HTTPException(422, "date must be YYYY-MM-DD")
    if body.time and not _TIME.match(body.time):
        raise HTTPException(422, "time must be HH-MM")
    if info.spec.cadence == "daily" and body.time:
        raise HTTPException(422, "daily reports take no time component")
    if info.spec.cadence == "intraday" and not body.time:
        raise HTTPException(422, "intraday reports require a time (HH-MM)")
    if len(body.html) > _MAX_HTML:
        raise HTTPException(413, "report html exceeds 2MB")
    clean = sanitize_report_html(body.html)
    run_id = getattr(request.state, "api_key_run_id", None)
    async with request.app.state.session_factory() as s:
        existing = (await s.execute(select(Report).where(
            Report.type == body.type, Report.date == body.date,
            Report.time == body.time))).scalar_one_or_none()
        if existing:
            existing.html, existing.title, existing.meta = clean, body.title, body.meta
            existing.run_id = run_id or existing.run_id
            report = existing
        else:
            report = Report(type=body.type, date=body.date, time=body.time,
                            title=body.title, meta=body.meta, html=clean,
                            run_id=run_id)
            s.add(report)
        await s.commit()
        return {"id": report.id, "type": report.type, "date": report.date,
                "time": report.time, "replaced": existing is not None}


def _meta_view(r: Report) -> dict:
    return {"id": r.id, "type": r.type, "date": r.date, "time": r.time,
            "title": r.title, "meta": r.meta, "run_id": r.run_id,
            "created_at": r.created_at.isoformat() if r.created_at else None,
            "updated_at": r.updated_at.isoformat() if r.updated_at else None}


@router.get("/api/reports", response_model=list[S.ReportMeta],
            dependencies=[Depends(require_role(*READ_ROLES))])
async def list_reports(request: Request, type: str | None = None,
                       date_from: str | None = None, date_to: str | None = None,
                       limit: int = 200):
    """Report metadata (no HTML) for calendars and lists, newest first. ISO
    date strings make the range filter lexicographic."""
    q = select(Report).order_by(Report.date.desc(), Report.time.desc())
    if type:
        q = q.where(Report.type == type)
    if date_from:
        q = q.where(Report.date >= date_from)
    if date_to:
        q = q.where(Report.date <= date_to)
    async with request.app.state.session_factory() as s:
        rows = (await s.execute(q.limit(min(limit, 1000)))).scalars().all()
    return [_meta_view(r) for r in rows]


@router.get("/api/reports/{report_id}", response_model=S.ReportDetail,
            dependencies=[Depends(require_role(*READ_ROLES))])
async def get_report(request: Request, report_id: str):
    """One report, sanitized fragment included. The web viewer injects the
    report-kit shell (tokens + report.css) around it."""
    async with request.app.state.session_factory() as s:
        r = await s.get(Report, report_id)
    if r is None:
        raise HTTPException(404, "unknown report")
    return {**_meta_view(r), "html": r.html}


@router.delete("/api/reports/{report_id}", response_model=S.Ok,
               dependencies=[Depends(require_admin)])
async def delete_report(request: Request, report_id: str):
    async with request.app.state.session_factory() as s:
        res = await s.execute(delete(Report).where(Report.id == report_id))
        await s.commit()
    if not res.rowcount:
        raise HTTPException(404, "unknown report")
    return {"ok": True}


@router.post("/api/report-kit/chart", response_model=S.ChartSvg,
             dependencies=[Depends(require_role(*ANNOTATE_ROLES))])
async def render_report_chart(spec: ChartSpec):
    """Server-rendered, theme-aware SVG for embedding in report fragments —
    reports carry no JavaScript, so charts are static markup (reportcharts).
    Colors are design-token vars resolved by the report-kit shell."""
    return {"svg": render_chart(spec)}
