import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { api, type ReportDetail, type ReportMeta, type ReportType } from "../api";
import ReportFrame from "../components/ReportFrame";
import { Button } from "@ap/ui/button";
import { Chip } from "@ap/ui/chip";

// Reports: dated HTML artifacts of git-declared report types
// (docs/design/11). Three views on one route family:
//   /reports              — the type grid
//   /reports/:type        — a month calendar of that type's instances
//   /reports/:type/:date  — the sandboxed viewer (?time=HH-MM for intraday)

// --- date helpers ------------------------------------------------------------

function ym(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}
function monthLabel(month: string): string {
  const [y, m] = month.split("-").map(Number);
  return new Date(y, m - 1, 1).toLocaleString(undefined, { month: "long", year: "numeric" });
}
function shiftMonth(month: string, by: number): string {
  const [y, m] = month.split("-").map(Number);
  return ym(new Date(y, m - 1 + by, 1));
}
function monthDays(month: string): (string | null)[] {
  // Cells for a Mon-first calendar grid: nulls pad the first week.
  const [y, m] = month.split("-").map(Number);
  const first = new Date(y, m - 1, 1);
  const pad = (first.getDay() + 6) % 7;
  const count = new Date(y, m, 0).getDate();
  return [
    ...Array.from({ length: pad }, () => null),
    ...Array.from({ length: count }, (_, i) => `${month}-${String(i + 1).padStart(2, "0")}`),
  ];
}
const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

// --- type grid ---------------------------------------------------------------

function TypeGrid() {
  const [types, setTypes] = useState<ReportType[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    api<ReportType[]>("/api/report-types").then(setTypes)
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load report types."));
  }, []);
  if (error) return <div className="error">{error}</div>;
  if (!types) return <p className="muted">Loading…</p>;
  return (
    <>
      <div className="page-header"><h1>Reports</h1></div>
      <p className="muted">
        Dated artifacts generated by agents. A report type is a building block
        (<code>reports/&lt;name&gt;/report.yaml</code>); instances land here.
      </p>
      {types.length === 0 && <p className="muted">No report types declared yet.</p>}
      <div className="report-type-grid">
        {types.map((t) => (
          <Link key={t.name} to={`/reports/${encodeURIComponent(t.name)}`} className="report-type-card">
            <div className="report-type-head">
              <span className="report-type-icon" aria-hidden>{t.icon || "📄"}</span>
              <span className="report-type-name">{t.name}</span>
              {t.error && <Chip variant="danger">broken</Chip>}
            </div>
            <p className="muted report-type-desc">{t.description || "—"}</p>
            <div className="report-type-foot muted">
              <span>{t.cadence}</span>
              <span>{t.count} {t.count === 1 ? "report" : "reports"}</span>
              {t.latest_date && <span>latest {t.latest_date}</span>}
            </div>
          </Link>
        ))}
      </div>
    </>
  );
}

// --- calendar ----------------------------------------------------------------

function TypeCalendar({ type }: { type: string }) {
  const [params, setParams] = useSearchParams();
  const month = params.get("m") ?? ym(new Date());
  const [reports, setReports] = useState<ReportMeta[] | null>(null);
  const [info, setInfo] = useState<ReportType | null>(null);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    api<ReportType[]>("/api/report-types")
      .then((ts) => setInfo(ts.find((t) => t.name === type) ?? null)).catch(() => {});
  }, [type]);
  useEffect(() => {
    api<ReportMeta[]>(`/api/reports?type=${encodeURIComponent(type)}&date_from=${month}-01&date_to=${month}-31`)
      .then(setReports)
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load reports."));
  }, [type, month]);

  const byDate = useMemo(() => {
    const m = new Map<string, ReportMeta[]>();
    for (const r of reports ?? []) {
      m.set(r.date, [...(m.get(r.date) ?? []), r]);
    }
    return m;
  }, [reports]);

  function open(day: string) {
    const list = byDate.get(day);
    if (!list?.length) return;
    const t = list.length > 1 ? "" : list[0].time;
    navigate(`/reports/${encodeURIComponent(type)}/${day}${t ? `?time=${t}` : ""}`);
  }

  if (error) return <div className="error">{error}</div>;
  return (
    <>
      <div className="page-header">
        <h1>
          <Link to="/reports" className="crumb">Reports</Link> / {info?.icon} {type}
        </h1>
        {info?.latest_date && (
          <Button variant="secondary" onClick={() => {
            const latest = (reports ?? []).find((r) => r.date === info.latest_date);
            navigate(`/reports/${encodeURIComponent(type)}/${info.latest_date}${latest?.time ? `?time=${latest.time}` : ""}`);
          }}>
            Open latest
          </Button>
        )}
      </div>
      {info?.description && <p className="muted">{info.description}</p>}
      <div className="cal-nav">
        <Button variant="secondary" size="sm" aria-label="Previous month"
                onClick={() => setParams({ m: shiftMonth(month, -1) })}>‹</Button>
        <span className="cal-month">{monthLabel(month)}</span>
        <Button variant="secondary" size="sm" aria-label="Next month"
                onClick={() => setParams({ m: shiftMonth(month, 1) })}>›</Button>
      </div>
      <div className="cal-grid" role="group" aria-label={`${type} reports, ${monthLabel(month)}`}>
        {WEEKDAYS.map((d) => <div key={d} className="cal-head">{d}</div>)}
        {monthDays(month).map((day, i) => {
          const list = day ? byDate.get(day) : undefined;
          const n = list?.length ?? 0;
          return day === null ? (
            <div key={`pad-${i}`} className="cal-cell cal-pad" />
          ) : (
            <button key={day} type="button" disabled={!n}
                    className={`cal-cell${n ? " cal-has" : ""}`}
                    onClick={() => open(day)}
                    aria-label={n ? `${day}: ${n} ${n === 1 ? "report" : "reports"}` : day}>
              <span className="cal-day">{Number(day.slice(-2))}</span>
              {n > 0 && <span className="cal-dot" aria-hidden>{n > 1 ? n : ""}</span>}
            </button>
          );
        })}
      </div>
      {reports !== null && reports.length === 0 && (
        <p className="muted">No {type} reports in {monthLabel(month)}.</p>
      )}
    </>
  );
}

// --- viewer ------------------------------------------------------------------

function Viewer({ type, date }: { type: string; date: string }) {
  const [params, setParams] = useSearchParams();
  const time = params.get("time") ?? "";
  const [dayReports, setDayReports] = useState<ReportMeta[] | null>(null);
  const [detail, setDetail] = useState<ReportDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    api<ReportMeta[]>(`/api/reports?type=${encodeURIComponent(type)}&date_from=${date}&date_to=${date}`)
      .then(setDayReports)
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load report."));
  }, [type, date]);

  const current = useMemo(() => {
    if (!dayReports?.length) return null;
    return dayReports.find((r) => r.time === time) ?? dayReports[dayReports.length - 1];
  }, [dayReports, time]);

  useEffect(() => {
    if (!current) return;
    api<ReportDetail>(`/api/reports/${current.id}`).then(setDetail)
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load report."));
  }, [current]);

  if (error) return <div className="error">{error}</div>;
  if (dayReports !== null && dayReports.length === 0) {
    return (
      <>
        <div className="page-header">
          <h1><Link to={`/reports/${encodeURIComponent(type)}`} className="crumb">{type}</Link> / {date}</h1>
        </div>
        <p className="muted">No report for {date}.</p>
      </>
    );
  }
  return (
    <>
      <div className="page-header">
        <h1>
          <Link to="/reports" className="crumb">Reports</Link> /{" "}
          <Link to={`/reports/${encodeURIComponent(type)}?m=${date.slice(0, 7)}`} className="crumb">{type}</Link>{" "}
          / {date}{current?.time ? ` ${current.time.replace("-", ":")}` : ""}
        </h1>
        <div className="report-nav-buttons">
          <Button variant="secondary" size="sm" onClick={() => navigate(`/reports/${encodeURIComponent(type)}?m=${date.slice(0, 7)}`)}>
            Calendar
          </Button>
        </div>
      </div>
      {(dayReports?.length ?? 0) > 1 && (
        <div className="report-times">
          {dayReports!.map((r) => (
            <button key={r.id} type="button"
                    className={`report-time-chip${r.id === current?.id ? " active" : ""}`}
                    onClick={() => setParams(r.time ? { time: r.time } : {})}>
              {r.time ? r.time.replace("-", ":") : "daily"}
            </button>
          ))}
        </div>
      )}
      {detail ? (
        <>
          <ReportFrame html={detail.html} title={detail.title || `${type} ${date}`} />
          <p className="muted report-provenance">
            {detail.title && <span>{detail.title} · </span>}
            generated {detail.updated_at ? new Date(detail.updated_at).toLocaleString() : "—"}
            {detail.run_id && <> · <Link to={`/runs/${detail.run_id}`}>run {detail.run_id.slice(0, 8)}</Link></>}
          </p>
        </>
      ) : (
        <p className="muted">Loading…</p>
      )}
    </>
  );
}

export default function Reports() {
  const { type, date } = useParams();
  if (type && date) return <Viewer type={type} date={date} />;
  if (type) return <TypeCalendar type={type} />;
  return <TypeGrid />;
}
