import type { Meta, StoryObj } from "@storybook/react-vite";
import reportKitCss from "./report-kit.css?raw";

// The report-kit: the blessed markup surface for agent-authored reports
// (docs/design/11). These stories ARE the contract — every rk-* class the
// backend sanitizer allows renders here. Charts are server-rendered SVG
// (POST /api/report-kit/chart); the samples below are captured output.

const meta: Meta = { title: "ReportKit/Elements" };
export default meta;

function Kit({ html }: { html: string }) {
  return (
    <>
      <style>{reportKitCss}</style>
      <main className="rk-page" dangerouslySetInnerHTML={{ __html: html }} />
    </>
  );
}

const CHART_BAR = `<svg role="img" class="rk-chart" viewBox="0 0 640 240" width="640" height="240" xmlns="http://www.w3.org/2000/svg"><line x1="36" y1="210" x2="632" y2="210" stroke="var(--ds-border)" stroke-width="1"/><rect x="60" y="90" width="80" height="120" rx="2" fill="var(--ds-chart-1)"/><rect x="209" y="130" width="80" height="80" rx="2" fill="var(--ds-chart-1)"/><rect x="358" y="50" width="80" height="160" rx="2" fill="var(--ds-chart-1)"/><rect x="507" y="150" width="80" height="60" rx="2" fill="var(--ds-chart-1)"/><text x="100" y="224" text-anchor="middle" font-family="inherit" fill="var(--ds-text-muted)" font-size="11">ai</text><text x="249" y="224" text-anchor="middle" font-family="inherit" fill="var(--ds-text-muted)" font-size="11">business</text><text x="398" y="224" text-anchor="middle" font-family="inherit" fill="var(--ds-text-muted)" font-size="11">infra</text><text x="547" y="224" text-anchor="middle" font-family="inherit" fill="var(--ds-text-muted)" font-size="11">misc</text></svg>`;
const SPARK = `<svg role="img" class="rk-sparkline" viewBox="0 0 120 32" width="120" height="32" xmlns="http://www.w3.org/2000/svg"><polyline points="2,26 22,18 42,22 62,10 82,14 102,6 118,12" fill="none" stroke="var(--ds-chart-1)" stroke-width="1.5"/><circle cx="118" cy="12" r="2.5" fill="var(--ds-chart-1)"/></svg>`;

export const FullReport: StoryObj = {
  render: () => (
    <Kit html={`
      <header class="rk-header">
        <h1 class="rk-title">Daily news — 2026-08-03</h1>
        <p class="rk-meta">gathered 07:00 · 23 items · 4 topics</p>
      </header>
      <div class="rk-stat-row">
        <div class="rk-stat"><span class="rk-stat-value">23</span><span class="rk-stat-label">items</span></div>
        <div class="rk-stat"><span class="rk-stat-value">4</span><span class="rk-stat-label">topics</span></div>
        <div class="rk-stat"><span class="rk-stat-value">${SPARK}</span><span class="rk-stat-label">14-day volume</span></div>
      </div>
      <div class="rk-callout">Top story: a major model release reshaped the coding-agent landscape.</div>
      <section class="rk-section">
        <h2>AI <span class="rk-chip rk-chip-accent">9 items</span></h2>
        <div class="rk-item">
          <span class="rk-item-title"><a href="https://example.com">Model X ships with 2M context</a></span>
          <span class="rk-item-src">example.com</span>
          <p class="rk-item-sum">The release focuses on long-horizon agentic work and cheaper caching.</p>
        </div>
        <div class="rk-item">
          <span class="rk-item-title"><a href="https://example.com">Eval suite goes open source</a></span>
          <span class="rk-item-src">example.com</span>
          <p class="rk-item-sum">A widely used private benchmark is now public, with a held-out split.</p>
        </div>
      </section>
      <section class="rk-section">
        <h2>Business <span class="rk-chip">3 items</span></h2>
        ${CHART_BAR}
      </section>
      <footer class="rk-footer">Generated by the news agent · daily-news · run 1a2b3c4d</footer>
    `} />
  ),
};

export const Elements: StoryObj = {
  render: () => (
    <Kit html={`
      <h2>Callouts</h2>
      <div class="rk-callout">Neutral/accent callout.</div>
      <div class="rk-callout rk-callout-warning">Warning callout.</div>
      <div class="rk-callout rk-callout-danger">Danger callout.</div>
      <div class="rk-callout rk-callout-success">Success callout.</div>
      <h2>Table</h2>
      <table><thead><tr><th>Topic</th><th>Items</th></tr></thead>
      <tbody><tr><td>ai</td><td>9</td></tr><tr><td>business</td><td>3</td></tr></tbody></table>
      <h2>Chips</h2>
      <p><span class="rk-chip">plain</span> <span class="rk-chip rk-chip-accent">accent</span></p>
      <h2>Grid</h2>
      <div class="rk-grid">
        <div class="rk-callout">left column</div>
        <div class="rk-callout">right column</div>
      </div>
      <h2>Prose</h2>
      <blockquote>Quoted context with a <code>code span</code>.</blockquote>
      <ul><li>list item one</li><li>list item two</li></ul>
    `} />
  ),
};
